export REDIS_HOST=redis-cluster-proxy.user-system-vaughnmedellins394
export REDIS_PASSWORD=EJtetarG2IAqYX8P
export MONGODB_HOST=mongo-cluster-mongos.user-system-vaughnmedellins394
export MONGODB_ACCOUNT=root-vaughnmedellins394-otmoiclp
export MONGODB_PASS=ANqAGivxFeLrEvgO
export MONGODB_DBNAME_LP_STORE=otmoiclp-vaughnmedellins394_lp_store
export STATUS_KEY=amm-market-status-report-price
export WRITE_FILELOG=true
