export OBRIDGE_LPNODE_DB_REDIS_MASTER_SERVICE_HOST=redis-cluster-proxy.user-system-jaclinannibale38
export REDIS_PASSWORD=54ujutPlBPWWDxrc
export MONGODB_HOST=mongo-cluster-mongos.user-system-jaclinannibale38
export MONGODB_ACCOUNT=root-jaclinannibale38-otmoiclp
export MONGODB_PASS=HgI6Q2Qiic30hX3r
export MONGODB_DBNAME_LP_STORE=otmoiclp-jaclinannibale38_lp_store