export REDIS_HOST=lp-redis
export REDIS_PASSWORD=Iqu7obyKqjuXKylq
export MONGODB_HOST=mongo-cluster-mongos.user-system-vaughnmedellins394
export MONGODB_ACCOUNT=root-vaughnmedellins394-otmoiclp
export MONGODB_PASS=tnQ6USGBYDcuW8Ci
export MONGODB_DBNAME_LP_STORE=otmoiclp-vaughnmedellins394_lp_store
export WRITE_FILELOG=true
